### ISSUE TITLE
Branch release/v7 (follow #35)

### ISSUE THREAD

**Issue by sergioaiello** [lvgl/lv_port_win_visual_studio#39]
Hi,
I can work yet with v7.
I did:
git clone https://github.com/lvgl/lv_sim_visual_studio.git
--recurse-submodules
cd lv_sim_visual_studio
git checkout release/v7
git submodule update

when I loaded the sln file I got an error window with the following
message:
---------------------------
One or more projects in the solution were not loaded correctly.
Please see the Output Window for details.
-------------------------

And Visual Studio did not open a workable project.
What's wrong?
Thank you for helping.

**Comment by MouriNaruto** [comment]
Please clone release/v7 branch directly. Because v8 branch is much different thanv7 branch.

> git clone -b release/v7 --recurse-submodules https://github.com/lvgl/lv_sim_visual_studio

Kenji Mouri
