### ISSUE TITLE
VS2019    Error C2664    copy example code to main()

### ISSUE THREAD

**Issue by txp666** [lvgl/lv_port_win_visual_studio#41]
Hello
when i copy example code to main() you can see this :
![image](https://user-images.githubusercontent.com/52451470/167536109-390eaa20-6ede-40fc-b6c5-37f0cff798b4.png)

**Comment by txp666** [comment]
![image](https://user-images.githubusercontent.com/52451470/167536816-2d0f960f-4539-408b-9a41-d2c30ac5a6b5.png)
i have to do this 
but why the code at example.c can run?   thank u

**Comment by MouriNaruto** [comment]
@txp666 

Because C and C++ are different. (The 'main' function is in the C++ source file, and LVGL examples are C source files.)

Kenji Mouri

**Comment by txp666** [comment]
thanks!
