### ISSUE TITLE
emulator bug

### ISSUE THREAD

**Issue by FarawayRay** [lvgl/lv_port_win_visual_studio#49]
The directory result for lvgl has changed, but the emulator configuration has not

**Comment by FarawayRay** [comment]
The directory result for lvgl has changed, but the emulator configuration has not changed

**Comment by MouriNaruto** [comment]
I need more detailed information about that, thanks.

Kenji Mouri

**Comment by FarawayRay** [comment]
The extra directory has been deleted, but the filter in the emulator still exists
in the file 'LVGL.Drivers.vcxitems' & 'LVGL.Portable.vcxitems'

**Comment by FarawayRay** [comment]
good plan,thank you
